# Generated by Django 6.0.5 on 2026-05-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('date', models.DateTimeField(verbose_name='Fecha y hora')),
                ('venue', models.CharField(max_length=200, verbose_name='Lugar')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='Capacidad total')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad disponible')),
                ('sold_quantity', models.PositiveIntegerField(default=0, verbose_name='Vendidos')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='evente.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Tipo de Boleto',
                'verbose_name_plural': 'Tipos de Boleto',
            },
        ),
    ]
