# Generated by Django 6.0.5 on 2026-05-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='has_numbered_seats',
            field=models.BooleanField(default=False, help_text='Activa si los boletos de este tipo tienen número de asiento asignado.', verbose_name='Asientos numerados'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='seat_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefijo para los asientos (ej: "A-", "VIP-"). Se numeran del 1 al total.', max_length=10, verbose_name='Prefijo de asiento'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad total'),
        ),
    ]
