# Generated by Django 6.0.5 on 2026-05-10 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('point_of_sale', '0002_ticket_seat_numbers_alter_ticket_ticket_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='Hora de entrada')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='point_of_sale.ticket', verbose_name='Boleto')),
            ],
            options={
                'verbose_name': 'Registro de Entrada',
                'verbose_name_plural': 'Registros de Entradas',
                'ordering': ['-entered_at'],
            },
        ),
    ]
