# Generated by Django 6.0.5 on 2026-05-10 00:32

import django.db.models.deletion
import point_of_sale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nombre del comprador')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='evente.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('ticket_number', models.CharField(default=point_of_sale.models._generate_ticket_number, max_length=20, unique=True, verbose_name='Número de boleto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='point_of_sale.sale', verbose_name='Venta')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evente.tickettype', verbose_name='Tipo de boleto')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
    ]
