# Generated by Django 6.0.5 on 2026-05-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evente', '0002_tickettype_has_numbered_seats_tickettype_seat_prefix_and_more'),
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Lista de asientos asignados (para tipos con asientos numerados).', verbose_name='Asientos'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_tickets', to='evente.tickettype', verbose_name='Tipo de boleto'),
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('items', models.JSONField(verbose_name='Items del pedido')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('mp_preference_id', models.CharField(blank=True, max_length=200, verbose_name='Preferencia MP')),
                ('mp_payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID de pago MP')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_orders', to='evente.event', verbose_name='Evento')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_order', to='point_of_sale.sale', verbose_name='Venta generada')),
            ],
            options={
                'verbose_name': 'Orden Pendiente (MP)',
                'verbose_name_plural': 'Órdenes Pendientes (MP)',
                'ordering': ['-created_at'],
            },
        ),
    ]
